spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sasha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
# Muestra qué filtros de seguridad se aplican a cada petición
logging.level.org.springframework.security=DEBUG
# Muestra los detalles de las consultas SQL y parámetros
logging.level.org.hibernate.orm.queries=DEBUG
# Esto te mostrará en consola qué JSON está intentando enviar el servidor
logging.level.org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor=DEBUG